# --------#
# General #
# --------#

# Default shell
set -g default-shell $SHELL

# Mouse
set -g mouse on

# History
set -g history-limit 102400

# Set windows and page index to base 1
set -g base-index 1
setw -g pane-base-index 1

# Re-number windows when creating/closing new windows
set -g renumber-windows on

# Use emacs key bindings in status line
set-option -g status-keys emacs

# Use vim key bindings in copy mode
setw -g mode-keys vi

# Fix ESC delay in vim
set -g escape-time 0

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty:RGB"

# ------------#
# Keybindings #
# ------------#

# Set prefix to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix


# Copy-mode
unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi 'C-v' send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Escape send-keys -X cancel

# Send command on double press
bind C-a send-prefix
bind C-l send-keys 'C-l'

# Reload tmux.conf on prefix r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Split panes and remember current path
bind '\' split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

# Remember current path when creating new windows
bind c new-window -c '#{pane_current_path}'

# Break pane into new window and keep focus on the current window
bind b break-pane -d

# Smart pane switching with awareness of Vim splits.
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n 'C-\' if-shell "$is_vim" "send-keys 'C-\'" "select-pane -l"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

bind [ previous-window
bind ] next-window

bind "{" select-window -t 1
bind "}" select-window -t :$

# -----------#
# Status bar #
# -----------#

set -g @tmux-dotbar-bg "default"
set -g @tmux-dotbar-fg "#a6a6a6"
set -g @tmux-dotbar-fg-current "#ff3b3b"
set -g @tmux-dotbar-fg-session "#808080"
set -g @tmux-dotbar-fg-prefix "#ffffff"

set -g @tmux-dotbar-window-status-format ' #I:#W '

run ~/.dotfiles/tmux/plugins/tmux-dotbar/dotbar.tmux

# -----------#
# Plugins    #
# -----------#

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

# --- ПЕРЕНАЗНАЧЕНИЕ КЛАВИШ ДЛЯ RESURRECT ---
set -g @resurrect-save 'S'

set -g @resurrect-restore 'R'

run '~/.tmux/plugins/tpm/tpm'
