#!/bin/bash

options=(
	style=round
	width=8.0
	hidpi=on
	# active_color="gradient(top_left=0xff00aeff,bottom_right=0xff642bff)" #blue-purple
	# active_color="gradient(top_left=0xff00aeff,bottom_right=0xcaffffff)" #blue-white
	active_color="gradient(top_left=0xca00ff7e,bottom_right=0xcaffffff)" #blue-white
	# active_color="gradient(top_left=0xffbb00ff,bottom_right=0xffff0000)"
	# inactive_color="gradient(top_left=0xffffffff,bottom_right=0xff00aeff)"
 	# inactive_color="gradient(top_left=0xff00aeff,bottom_right=0xff642bff)"
	# gradient(top_left=0xAARRGGBB,bottom_right=0xAARRGGBB)
	#  gradient(top_right=0xAARRGGBB,bottom_left=0xAARRGGBB)
	#  glow(0xAARRGGBB)
)

borders "${options[@]}"
